from brownie import accounts, config, SimpleStorage, network

def deploy_simple_storage():
    '''
    '''
    # In this one, it retrieves the first key generated by ganache
    account = get_account()
    # Retrieve a stored account
    # account = accounts.load('metamask-testing')
    # Retrieve account from environment using config.yaml
    # account = accounts.add(config['wallets']['from_key'])
    simple_storage = SimpleStorage.deploy({'from': account})
    stored_value = simple_storage.retrieve()
    transaction = simple_storage.store(15, {'from': account})
    transaction.wait(1)
    updated_stored_value = simple_storage.retrieve()
    print(f'Before: {stored_value} and after {updated_stored_value}')


def get_account() -> str:
    if network.show_active() == 'development':
        return accounts[0]
    else:
        return accounts.add(config['wallets']['from_key'])



def main():
    deploy_simple_storage()